# 服务器配置
server:
    port: 8092
# 配置环境配置
spring:
    profiles:
        active: prod
    # 数据源配置
    datasource:
        username: root
        password: 123456
        # 注意时区
        url: jdbc:mysql://127.0.0.1:3306/test?serverTimezone=CTT&useSSL=false&useUnicode=true&characterEncoding=utf8
        #driver-class-name: com.mysql.jdbc.Driver
    # 模板引擎
    freemarker:
        #内容格式
        content-type: text/html
        #缓存配置
        cache: false
        #模板路径
        template-loader-path: classpath:/templates
        #编码格式
        charset: UTF-8
        #是否启用
        enabled: true
        #请求内容属性
        request-context-attribute: request
        expose-request-attributes: true
        expose-session-attributes: true
        #检查模板路径
        check-template-location: true
        #文件后缀
        suffix: .ftl
    # Redis配置
    redis:
        database: 0
            host: 127.0.0.1
            port: 6379
            password: redis
            jedis:
                pool:
                    max-active: 8
                    max-idle: 8
                    max-wait: -1ms
                    min-idle: 0
            timeout: 600
#参考文章：https://blog.51cto.com/14230003/2405833
rocketmq:
    common:
        # 生产者配置
        producer:
            isOnOff: on
            # 发送同一类消息的设置为同一个group，保证唯一
            groupName: FeePlatGroup
            # 服务地址
            namesrvAddr: 127.0.0.1:9876
            # 消息最大长度 默认1024*4(4M)
            maxMessageSize: 4096
            # 发送消息超时时间,默认3000
            sendMsgTimeout: 3000
            # 发送消息失败重试次数，默认2
            retryTimesWhenSendFailed: 2
        # 消费者配置
        consumer:
            isOnOff: on
            # 官方建议：确保同一组中的每个消费者订阅相同的主题。
            groupName: FeePlatGroup
            # 服务地址
            namesrvAddr: 127.0.0.1:9876
            # 接收该 Topic 下所有 Tag
            topics: FeePlatTopic~*;
            consumeThreadMin: 20
            consumeThreadMax: 64
            # 设置一次消费消息的条数，默认为1条
            consumeMessageBatchMaxSize: 1
            # 主题
            topic: mytopic
            # 标签
            tag: mytag
    advance:
        # 生产者配置
        producer:
            isOnOff: on
            # 发送同一类消息的设置为同一个group，保证唯一
            groupName: AdvanceGroup
            # 服务地址
            namesrvAddr: 127.0.0.1:9876
            # 消息最大长度 默认1024*4(4M)
            maxMessageSize: 4096
            # 发送消息超时时间,默认3000
            sendMsgTimeout: 3000
            # 发送消息失败重试次数，默认2
            retryTimesWhenSendFailed: 2
            # 主题
            topic: advance
            # 标签
            tag: advance_tag
            # 动物专题配置
            animal:
                # 主题
                topic: animal
                # 标签
                tag: panda
        # 消费者配置
        consumer:
            isOnOff: on
            # 官方建议：确保同一组中的每个消费者订阅相同的主题。
            groupName: AdvanceGroup
            # 服务地址
            namesrvAddr: 127.0.0.1:9876
            # 接收该 Topic 下所有 Tag
            topics: AdvanceGroup~*;
            consumeThreadMin: 20
            consumeThreadMax: 64
            # 设置一次消费消息的条数，默认为1条
            consumeMessageBatchMaxSize: 1
            # 主题
            topic: advance
            # 标签
            tag: advance_tag
            # 动物专题配置
            animal:
                # 主题
                topic: animal
                # 标签
                tag: panda
# 配置 Group  Topic  Tag
fee-plat:
    fee-plat-group: FeePlatGroup
    fee-plat-topic: FeePlatTopic
    fee-account-tag: FeeAccountTag